### ISSUE TITLE
Radio select (group as button select)

### ISSUE THREAD

**Issue by ghost** [alispx/Mie-Customizer#3]
Hi there,
Please could you make an update so that we have an option to used a grouped button as radio select.

You can see here what I mean. (I will like to use this field type for dependency control as well).

![screen shot 2015-06-09 at 11 50 51 am](https://cloud.githubusercontent.com/assets/1312880/8049387/d9bd8550-0e9d-11e5-8b35-75f81405f49b.png)

**Comment by agusmu** [comment]
I see that Kirki uses jQuery UI for this radio-buttonset type. 

I think we can use bundled jQuery UI for this one.

**Comment by agusmu** [comment]
@cmwwebfx I close this one, you can check my latest commit on c83495a8ce89c48fbf144de57ca80a6e8db18a2c

the usage of buttonset is similar with radio type, you only need to change the type to "buttonset"

```
            $mie_options[] = array( 
                'slug'      => 'mie_example_buttonset_field', 
                'default'   => 'option_2', 
                'priority'  => 1, 
                'label'     => __( 'Buttonset Field', '_mie' ),
                'section'   => 'mie_buttonset_settings',
                'type'      => 'buttonset',
                'choices'  => array(
                    'option_1' => __( 'Option 1', '_mie' ),
                    'option_2' => __( 'Option 2', '_mie' ),
                    'option_3' => __( 'Option 3', '_mie' ),
                ),
            );
```

**Comment by ghost** [comment]
Hi mate.  First of all congrats with the little one on the way. Saw the pictures this morning.  

Do you have a screenshot of the button set please.

**Comment by agusmu** [comment]
Check this image, I made custom jQuery UI theme that match Customizer style.

<img width="154" alt="mie-buttonset" src="https://cloud.githubusercontent.com/assets/1005437/8505910/ebdda8c6-2222-11e5-99ad-70d88f54cb2e.png">

**Comment by ghost** [comment]
So Shiney.  It is beautiful. Love it
